version: '3.8'

services:
  backend:
    build: ./server
    container_name: backend
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
