name: App CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Build Docker containers
        run: docker-compose build

      - name: Start containers in background
        run: docker-compose up -d

      - name: Wait for services to be ready
        run: sleep 10

      - name: Check running containers
        run: docker ps

      - name: Backend Logs
        run: docker logs backend

      - name: Frontend Logs
        run: docker logs frontend
