name: App CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Build Docker containers
        run: docker-compose build

      - name: List Docker images
        run: docker images

      - name: Run containers (foreground)
        run: docker-compose up --abort-on-container-exit

      - name: List containers (detailed)
        run: docker ps -a

      - name: Check container exit codes
        run: |
          for container in backend frontend; do
            echo "$container exit code:"
            docker inspect -f '{{.State.ExitCode}}' $container || true
          done

      - name: Backend Logs
        if: failure()
        run: docker logs backend || true

      - name: Frontend Logs
        if: failure()
        run: docker logs frontend || true
